### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by Wh1t3Rose** [kt5company/discord-uptimerobot#4]
Configured data/db.json with proper Monitor ID in the value field (Only testing one ID at the moment for http url)

Also filled auth.json with Bot Token and Uptime API Key (using the full access API Key for testing)

Finally I filled info.json with My Discord ID, prefix, Server ID and Channel ID

```
(node:287) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/scripts/discord-uptimerobot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/scripts/discord-uptimerobot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/scripts/discord-uptimerobot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at cl.getMonitors.then (/scripts/discord-uptimerobot/commands/service.js:51:14)
    at /scripts/discord-uptimerobot/node_modules/promise/lib/core.js:33:15
    at flush (/scripts/discord-uptimerobot/node_modules/asap/asap.js:27:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ktg5** [comment]
What version of node.js are you running?

**Comment by Wh1t3Rose** [comment]
@ktg5 v10.19.0

**Comment by ktg5** [comment]
Please update to node.js v12 or higher, Discord.js v12 requires node.js v12+.

**Comment by Wh1t3Rose** [comment]
I am not a developer. Just a sys admin trying to get this up and running. I guess my version is too old?

**Comment by Wh1t3Rose** [comment]
OK thank you!

**Comment by ktg5** [comment]
Np.
